<br /><br />

<div id="view-content">
  <h2>Access Log</h2>            
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>Url</th>
        <th>Endereço de IP</th>
        <th>Data de acesso</th>
        <th>Protocolo</th>
        <th>Método</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($this->requests as $request): ?>
      <tr>
        <td><?php echo $request['_id'] ?></td>
        <td><?php echo $request['uri'] ?></td>
        <td><?php echo $request['ipAddr'] ?></td>
        <td><?php echo $request['accessDate'] ?></td>
        <td><?php echo $request['protocol'] ?></td>
        <td><?php echo $request['method'] ?></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>